#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_Matrix_S1_1, motorD,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, motorE,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motorF,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, irSvo,                tServoStandard)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifndef NO_UNIT_TEST
#endif
// As a programmer I want to create a steering command to drive toward the IR beacon so that can score points
//
//======================================================//
// Usage:
//   #pragma config(Sensor, S1,     irSensor,       sensorHiTechnicIRSeeker1200) // IR sensor must be called irSensor
//   #define NO_UNIT_TEST // Ignore the unit tests of include files
//
//  Notes: Region to the left (top view) 1,2,3,4 Forward 5, region to right 6,7,8,9
//    Use transtions between regions to set a steering command.
//          5-4,4-3,3-2,2-1,1-0
//          5-6,6-7,7-8,8-9,9-0
#define IR_TRANSITION_1 10 // Transition 5-4 or 5-6
#define IR_TRANSITION_2 20 // Transition 4-3 or 6-7
#define IR_TRANSITION_3 30 // Transition 3-2 or 7-8
#define IR_TRANSITION_4 40 // Transition 2-1 or 8-9
#define IR_TRANSITION_5 50 // Transition 1-0 or 9-0
int irSensorOld=0;
int irSensorCur=0;
int irSensorSteeringCmd=0;

int IrSensCmd(){
	irSensorOld = irSensorCur;
	irSensorCur = SensorValue[irSensor];

	if ((irSensorCur==5&&(irSensorOld==6||irSensorOld==4))||
			(irSensorOld==5&&(irSensorCur==6||irSensorCur==4)))
		irSensorSteeringCmd=IR_TRANSITION_1;
	else if ((irSensorCur==4&&irSensorOld==3)||(irSensorCur==6&&irSensorOld==7)||
					 (irSensorOld==4&&irSensorCur==3)||(irSensorOld==6&&irSensorCur==7))
		irSensorSteeringCmd=IR_TRANSITION_2;
	else if ((irSensorCur==3&&irSensorOld==2)||(irSensorCur==7&&irSensorOld==8)||
					 (irSensorOld==3&&irSensorCur==2)||(irSensorOld==7&&irSensorCur==8))
		irSensorSteeringCmd=IR_TRANSITION_3;
	else if ((irSensorCur==2&&irSensorOld==1)||(irSensorCur==8&&irSensorOld==9)||
					 (irSensorOld==2&&irSensorCur==1)||(irSensorOld==8&&irSensorCur==9))
		irSensorSteeringCmd=IR_TRANSITION_4;

	return(irSensorSteeringCmd);
}
// ==================UNIT TEST==========================//
#ifndef NO_UNIT_TEST
#include "i_debug.c"
int timeLeft=0; // A global variable used to adjust the time it takes to complet the while loop
int i=0;
short sm_cmd=0;
int irSvoVal=1;
bool runTest=true;
#define INC 0
#define DEC 1
#define FOREGROUND_MS 50 //The while loop takes 50 MS to run. This means the software runs 20 times per second
task main(){
	// Initialize variables here //
	int myInt=0;
	int in=0;
	int out=0;
	int out2;
	//Debug2File(); //Send the debug information to the file debug.txt
	//Debug2NXT();  //Send the debug information to the NXT screen
	Debug2Stream(); //Send the debug information to the PC Screen

	// End of initialize //
	while(runTest){
		clearTimer(T1);
		hogCPU(); //Prevent other tasks from running when this one is.
		// ------------- Put Unit Test code here -------------------//
		// xxxxxxx [] Transition 5-6 or 6-5 or 4-5 or 5-4 sends out IR_TRANSITION_1
		// xxxxxxx [] Transition 6-7 or 7-6 or 3-4 or 4-3 sends out IR_TRANSITION_2
		// xxxxxxx [] Transition 7-8 or 8-7 or 2-3 or 3-2 sends out IR_TRANSITION_3
		// xxxxxxx [] Transition 8-9 or 9-8 or 1-2 or 2-1 sends out IR_TRANSITION_4
		// xxxxxxx [] Transition 9-0 or 0-9 or 0-1 or 1-0 does not change output

		// ------- Move IR Servo -----//
		switch (sm_cmd) {
		case INC:
			if (irSvoVal>255) sm_cmd=DEC;
			irSvoVal+=3;
		break;
		case DEC:
			if (irSvoVal<1) runTest=false;
			irSvoVal-=3;
		break;
		}
		servo[irSvo]=irSvoVal;


		// USAGE NOTES:
		//   The units for a are encoder clicks
		//   Set #define NO_UNIT_TEST
		out=IrSensCmd();

		out2=IRGetACDir(irSensor);
		if (irSensorCur!=irSensorOld){
			DebugInt("SenOld",irSensorOld);
			DebugInt("SenCur",irSensorCur);
			DebugInt("SenCmd",out);
			DebugInt("Svo",irSvoVal);
			DebugPrint();
		}

		i+=1; // Increment the frame counter for unit test
		// ------------- Unit code test is done here ---------------//
		timeLeft=FOREGROUND_MS-time1[T1]; // Calculate the time used in the foreground
		releaseCPU(); // Let other tasks run now.
		wait1Msec(timeLeft);// The time other tasks have to run before foreground takes control.
	}// While Loop
}// Main Task
#endif
