#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    Arm,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    Finger,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    Elbow,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    Wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    Waist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("joystickSimple");
#include "JoystickDriver.c"
#include "i_debug.c"
#include "i_limit.c"
#include "i_RateLimit.c"
#include "i_integrate.c"
#include "i_deadzone.c"

int timeLeft=0; // A global variable that sticks around each frame
float b1PosZ1=160; // Finger
float y1PosZ1=85; // Wrist
float x1PosZ1=129; // Elbow
float y2PosZ1=180; // Arm
float x2PosZ1=139; // Waist
// Finger, Wrist, Elbow, Arm, Waist
int path[][]={
		{160, 85, 129, 180, 139},
		{160, 85, 129, 180, 139}};

		//joystick.joy1_TopHat == 0
// ------------------------Foreground Task -----------------------------//
// Run every second
#define FOREGROUND_MS 50 //I change this to 50 when I control the robot. 1000 is good for testing.
#define DT (float)FOREGROUND_MS/1000
task main(){

  int tmp;
  Debug2Stream();

	while(true){
		ClearTimer(T1);
		hogCPU(); //Prevent other tasks from running when this one is.

    // Read in the joystick commands
    getJoystickSettings(joystick);

    tmp=0;
    if (joy1Btn(05) == 1) tmp=30;
    if (joy1Btn(06) == 1) tmp=-30;
	  DebugInt("FgrBtn",tmp);
    tmp = Integrate(tmp, 110, 180, DT, b1PosZ1);
	  DebugInt("Fgr",tmp);
    servo[Finger]=tmp;

    tmp = Integrate(DeadZone(joystick.joy1_y1, 3), 0, 250, DT, y1PosZ1);
	  DebugInt("Wrst",tmp);
    servo[Wrist]=tmp;


    tmp = Integrate(DeadZone(joystick.joy1_x1/2, 3), 50, 175, DT, x1PosZ1);
	  DebugInt("Elb",tmp);
    servo[Elbow]=tmp;

    tmp = Integrate(DeadZone(-joystick.joy1_y2/2, 3), 110, 180, DT, y2PosZ1);
	  DebugInt("Arm",tmp);
    servo[Arm]=tmp;

    tmp = Integrate(DeadZone(-joystick.joy1_x2/2, 3), 0, 255, DT, x2PosZ1);
	  DebugInt("Waist",tmp);
    servo[Waist]=tmp;

    // y2->x2 Waist->Elb
    // x2->x1 Elb->Fgr

    DebugPrint();
	  timeLeft=FOREGROUND_MS-time1[T1]; // Calculate the time used in the foreground
	  releaseCPU(); // Let other tasks run now.
	  wait1Msec(timeLeft);// The time other tasks have to run before foreground takes control.

	}// While Loop
}// Foreground Task
